// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeAgent.Web.Features.PullRequests.Data;

#nullable disable

namespace TreeAgent.Web.Migrations
{
    [DbContext(typeof(TreeAgentDbContext))]
    partial class TreeAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Feature", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GitHubPRNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("main");

                    b.Property<string>("DefaultPromptTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultSystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubRepo")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPromptTemplateId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.SystemPromptTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SystemPromptTemplates");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Agent", b =>
                {
                    b.HasOne("TreeAgent.Web.Data.Entities.Feature", "Feature")
                        .WithMany("Agents")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Feature", b =>
                {
                    b.HasOne("TreeAgent.Web.Data.Entities.Feature", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TreeAgent.Web.Data.Entities.Project", "Project")
                        .WithMany("Features")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Message", b =>
                {
                    b.HasOne("TreeAgent.Web.Data.Entities.Agent", "Agent")
                        .WithMany("Messages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Project", b =>
                {
                    b.HasOne("TreeAgent.Web.Data.Entities.SystemPromptTemplate", "DefaultPromptTemplate")
                        .WithMany()
                        .HasForeignKey("DefaultPromptTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultPromptTemplate");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.SystemPromptTemplate", b =>
                {
                    b.HasOne("TreeAgent.Web.Data.Entities.Project", "Project")
                        .WithMany("PromptTemplates")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Agent", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Feature", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("TreeAgent.Web.Data.Entities.Project", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("PromptTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
