namespace Homespun.Shared.Requests;

/// <summary>
/// Request model for generating a branch ID.
/// </summary>
/// <param name="Title">The issue title to generate a branch ID from</param>
public record GenerateBranchIdRequest(string Title);

/// <summary>
/// Response model for branch ID generation.
/// </summary>
/// <param name="Success">Whether the generation succeeded</param>
/// <param name="BranchId">The generated branch ID if successful</param>
/// <param name="Error">Error message if failed</param>
/// <param name="WasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization</param>
public record GenerateBranchIdResponse(
    bool Success,
    string? BranchId,
    string? Error,
    bool WasAiGenerated);

/// <summary>
/// Request to start action queue execution on a root issue.
/// </summary>
public class StartActionQueueRequest
{
    /// <summary>
    /// The root issue ID to start execution from.
    /// </summary>
    public required string IssueId { get; set; }
}

/// <summary>
/// Response for action queue status with per-queue breakdown and overall progress.
/// </summary>
public class ActionQueueStatusResponse
{
    public required string ProjectId { get; set; }
    public required string Status { get; set; }
    public string? RootIssueId { get; set; }
    public int MaxConcurrency { get; set; }
    public int RunningQueueCount { get; set; }
    public List<ActionQueueDetail> Queues { get; set; } = [];

    /// <summary>
    /// Total number of queues for this project across all pages.
    /// </summary>
    public int TotalQueueCount { get; set; }

    public int Limit { get; set; }
    public int Offset { get; set; }

    /// <summary>
    /// Overall progress across all queues — always computed across the full queue set.
    /// </summary>
    public ActionQueueProgress Progress { get; set; } = new();
}

/// <summary>
/// Detail for a single action queue.
/// </summary>
public class ActionQueueDetail
{
    public required string Id { get; set; }
    public required string State { get; set; }
    public string? CurrentIssueId { get; set; }
    public int PendingCount { get; set; }
    public List<ActionQueueHistoryEntry> History { get; set; } = [];
}

/// <summary>
/// A completed issue execution record.
/// </summary>
public class ActionQueueHistoryEntry
{
    public required string IssueId { get; set; }
    public bool Success { get; set; }
    public string? Error { get; set; }
    public DateTimeOffset StartedAt { get; set; }
    public DateTimeOffset CompletedAt { get; set; }
}

/// <summary>
/// Overall progress across all action queues.
/// </summary>
public class ActionQueueProgress
{
    public int TotalIssues { get; set; }
    public int Completed { get; set; }
    public int Failed { get; set; }
    public int Remaining { get; set; }
}
